##########################
## Site Config Settings ##
##########################

# Theme version
version: 2.0.4

# Theme tone
dark: true #true/false

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: /archives/
    icon: fa-archive
  - page: playlist
    directory: /playlist/
    icon: fa-empty
  - page: about
    directory: /about/
    icon: fa-user
  - page: rss
    directory: /atom.xml
    icon: fa-rss

# Sidebar
widgets:
  - recent_posts
  - category
  - tag
  - archive
  #- weibo
  - links

# Toc
toc:
  enable: true
  number: false

# Static files
js: js
css: css
share_path: share

# Date_formats
date_formats:
  archive: "MM月DD日"
  category: "YYYY/MM/DD"
  post: "MMM DD, YYYY"
  tag: "YYYY/MM/DD"

# Extensions
Plugins:
  hexo-generator-sitemap
  hexo-generator-baidu-sitemap

#sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

#Local search
local_search: true ## Use a javascript-based local search engine, true/false.

#Copyright
copyright: 
  enable: true #display article copyright information, true/false.
  describe: #copyright description

# MathJax Support
mathjax:
  enable: false  #true/false.
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

#Cmments
comment:
  duoshuo: #chaooo ## duoshuo_shortname
  disqus: ## disqus_shortname
  livere: ## 来必力(data-uid)
  uyan: ## 友言(uid)
  cloudTie: ## 网易云跟帖(productKey)
  changyan: ## 畅言需在下方配置两个参数，此处不填。
    appid: ## 畅言(appid)
    appkey: ##畅言(appkey)
  gitalk:
    enable: true ## If you want to use Gitment comment system please set the value to true.
    owner: jmzc4j ## Your GitHub ID, e.g. username
    repo: blog-comment ## The repository to store your comments, make sure you're the repo's owner
    client_id: '364a9cca58ff5a95c1ee' ## GitHub client ID
    client_secret: '1e16b6ba1daa2fddefd4de819db82b9a01f6406f' ## GitHub client secret
    admin: jmzc4j ## Github repo owner and collaborators, only these guys can initialize github issues.
    language: zh-CN ## Language
    pagerDirection: last # Comment sorting direction, available values are last and first.

#Share
share:
  local_share: true ##本地分享
  baidu_share: #true ## 百度分享
  JiaThis_share: ##true ##JiaThis分享
  duoshuo_share: #true ##true 多说分享必须和多说评论一起使用。
  addToAny_share: # AddToAny share. Empty list hides. List items are service name at url. For ex: email for '<a href="https://www.addtoany.com/add_to/email?linkurl=...'
  #  - twitter
  #  - baidu
  #  - facebook
  #  - google_plus
  #  - linkedin
  #  - email

# Analytics
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42025684-2
baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 1006843030519956000

# Miscellaneous
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
busuanzi: true ## If you want to use Busuanzi page views please set the value to true.

# About page
about:
  photo_url: /img/45.jpg ## Your photo 
  items:
  - label: email
    url: mailto:jmzc_top@aliyun.com ## Your email with mailto:
    title: jmzc_top@aliyun.com ## Your email 
  - label: github
    url:  https://github.com/jmzc4j ## Your github'url 
    title: jmzc4j ## Your github'name 
  - label: weibo
    url: https://weibo.com/u/1720363717 ## Your weibo's url 
    title: H_3W ## Your weibo's name 
# - label: twitter
#   url: 
#   title:
# - label: facebook
#   url:
#   title:

# Links widget. Empty links will hide widget.
links:
  - title: Hexo官网网站
    url: https://hexo.io/zh-cn/
  - title: Alibaba Java开发规范
    url: https://blog.csdn.net/shijunwang/article/details/79550994
  - title: MarkDown基本语法
    url: https://www.jianshu.com/p/b03a8d7b1719
